# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow integrates Pyre with GitHub's
# Code Scanning feature.
#
name: ABOTautomation
on: [push]
jobs:
  build:
    - runs-on: ubuntu-latest
    - name: set up Python 3.11.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if[ -f requirements.txt ]; then pip install -r requirements.txt;fi
    - uses: actions/setup-python@v3
      if: success() || failure()
    - run: |
        cd wegonTest
        mkdir -p reports
        pytest --alluredir=Reports
        chmod 777 /home/runner/work/python-se/python-se/tests/reports
    - name: Set Output
      if: success() || failure()
      id: results
    - run: echo "acrtifactPath=tests/reports/" >> $GITHUB_OUTPUT

    - uses: actions/setup-python@v3
      if: success() || failure()
      with:
        name: test-report
        path: ${{steps.results.outputs.artifactpath }}
