name: ABOTautomation

on:
  push:
    branches: ["ABOTAutoPytest"]

jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.11.7
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.7"

      - name: Install dependencies
        run:
          pip install --upgrade pip
          pip install pytest 
          pip install allure-pytest

      - name: Install other dependencies
        run: |
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          fi

      - name: Create reports directory
        run: mkdir -p reports

      - name: Run tests and generate allure reports
        run: |
          pytest test_UITests_test.py --alluredir=reports

      - name: Set Output
        id: results
        run: echo "::set-output name=artifactPath::reports/"

      - name: Upload test reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: ${{ steps.results.outputs.artifactPath }}
