name: ABOTautomation

on:
  workflow_dispatch:
    schedule:
      - cron: '*/5 * * * *'
  push:
    branches:
permissions:
  contents: write

jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
      - name: install chrome
        run: |
          sudo -E apt -f install -y
          sudo -E apt-get install -y wget
          sudo -E wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo -E apt-get install -y google-chrome-stable
      - name: Set up Python 3.11.7
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.7"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run:
          pip install --upgrade pip
          pip install pytest
          pip install allure-pytest
          pip install typing_extensions==4.7.1 --upgrade
          pip install selenium==4.17.0
          pip install allure-pytest
          pip install allure-python-commons==2.13.2
          pip install -U deepeval
          pip install telnetlib3
#          pip install pytest-allure-adaptor

#      - name: Install other dependencies
#        run: |
#          if [ -f "requirements.txt" ]; then
#            pip install -r requirements.txt
#          fi

      - name: Create reports directory
        run: mkdir -p reports

      - name: Run tests and generate allure reports
        run: |
          cd Tests/
          pytest test_LoginLogout_test.py --alluredir=../reports

      - name: Add allure information
        working-directory: allure-results
        if: always()
        run: |
            - name: Allure results
            uses: simple-elf/allure-report-action@master
            if: always()
            id: allure-report
            with:
              allure_results: allure-results
              allure_report: allure-report
              gh_pages: gh-pages
              allure_history: allure-history
          - name: Deploy report to Github Pages
            if: always()
            uses: peaceiris/actions-gh-pages@v3
            with:
              PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              PUBLISH_BRANCH: gh-pages
              PUBLISH_DIR: allure-history

