name: ABOTautomation

on:
  push:
    branches:
      - ABOTAutoPytest

jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Chrome
        run: |
          sudo apt update
          sudo apt install -y wget
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt -f install -y
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
            java-version: '11'

      - name: Install Allure
        run: |
                sudo apt-add-repository ppa:qameta/allure
                sudo apt-get update 
                sudo apt-get install allure
      - name: Set up Python 3.11.7
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.7"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest
          pip install typing_extensions==4.7.1 --upgrade
          pip install selenium==4.17.0
          pip install allure-pytest
          pip install allure-python-commons==2.13.2
          pip install -U deepeval
          pip install telnetlib3
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          fi
      - name: Create reports directory
        run: mkdir -p reports
      - name: Run tests and generate Allure reports
        run: |
          cd Tests/
          python -m pytest test_UITests_test.py --alluredir=../reports
      - name: Set Output
        id: results
        run: echo "::set-output name=artifactPath::reports"
      - name: Generate Allure report
        run: allure generate ../reports --clean -o ../allure-report
      - name: Publish Allure report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report