name: ABOTautomation

on:
  push:
    branches:
      - ABOTAutoPytest

jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.11.7
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.7"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run:
          pip install --upgrade pip
          pip install pytest
          pip install allure-pytest

      - name: Install other dependencies
        run: |
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          fi

      - name: Create reports directory
        run: mkdir -p reports

      - name: Run tests and generate allure reports
        run: |
          cd Tests/
          python -m pytest test_UITests_test.py --alluredir=../reports

      - name: Generate Allure report
        run: allure generate reports --clean -o allure-report
          - name: Publish Allure report
            uses: actions/upload-artifact@v2
            with:
              name: allure-report
              path: allure-report
