name: ABOTautomation

on:
  workflow_dispatch:
    schedule:
      - cron: '*/5 * * * *'
  push:
    branches:
permissions:
  contents: write

jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
      - name: install chrome
        run: |
          sudo -E apt -f install -y
          sudo -E apt-get install -y wget
          sudo -E wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo -E apt-get install -y google-chrome-stable
      - name: Set up Python 3.11.7
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.7"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run:
          pip install --upgrade pip
          pip install pytest
          pip install allure-pytest
          pip install typing_extensions==4.7.1 --upgrade
          pip install selenium==4.17.0
          pip install allure-pytest
          pip install allure-python-commons==2.13.2
          pip install -U deepeval
          pip install telnetlib3

#      - name: Install other dependencies
#        run: |
#          if [ -f "requirements.txt" ]; then
#            pip install -r requirements.txt
#          fi

      - name: Create reports directory
        run: mkdir -p reports

      - name: Run tests and generate allure reports
        run: |
          cd Tests/
          pytest --alluredir=../reports

      - name: Set Output
        id: results
        run: echo "::set-output name=artifactPath::reports"

      - name: Upload test reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: ${{ steps.results.outputs.artifactPath }}
